site_name: Trainees-FiSi
# repo_name: Kubernetes-Collection
# repo_url: https://github.com/ITLab-CC/Kubernetes-Collection
# edit_uri: 'tree/main/Docs/docs/'
# site_url: https://itlab-cc.github.io/Kubernetes-Collection/
theme:
  name: material
  features:
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - navigation.footer
    - navigation.expand
    - navigation.indexes
  palette:
    scheme: slate
  custom_dir: overrides
extra_javascript:
  - javascripts/quiz.js
extra_css:
  - stylesheets/quiz.css
markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - awesome-pages
  - git-revision-date
  - encryptcontent:
      password_inventory:
        add_infos: iamfinished
  - print-site
nav:
  - Home: index.md
  - First Start:
      - first_start/index.md
  - Mininet:
      - ... | mininet/*.md
  - Virtualization:
      - Proxmox: virtualization/proxmox.md
      - Docker: virtualization/docker.md
  - Networking:
      - Basics:
          - Subnetting: networking/basics/subnetting.md
      - Firewall: networking/firewall.md
      - Switch: networking/switch.md
      - VLAN: networking/vlan.md
  - Services:
      - Intro: services/introduction.md
      - ... | services/*.md
  - Wifi:
      - Controller: wifi/controller.md
      - APs: wifi/aps.md
  - VPN:
      - ... | vpn/*.md
