site_name: Trainees-FiSi
repo_name: Trainees-FiSi
repo_url: https://github.com/skyface753/Trainees-FiSi
edit_uri: 'tree/main/docs/'
site_url: https://skyface753.github.io/Trainees-FiSi/
theme:
  name: material
  features:
    - content.code.copy
    # Disabled, because it prevents the js for the quiz from working
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    # - navigation.footer
    # - navigation.expand
    - navigation.indexes
    - navigation.top
  palette:
    scheme: slate
extra_css:
  - css/neoteroi-mkdocs.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - neoteroi.timeline
  - toc:
      permalink: true
plugins:
  - search
  - awesome-pages
  - git-revision-date
  - mkdocs_quiz
  - open-in-new-tab
  - thumbnails:
      style: margin-top:5px;margin-bottom:5px;margin-right:25px
  # Last plugin
  - print-site
# Nav gets generated by `.pages` files in the folders
# Add new folders to the `docs/.pages` file
