site_name: Trainees-FiSi
repo_name: Trainees-FiSi
repo_url: https://github.com/skyface753/Trainees-FiSi
edit_uri: 'tree/main/docs/'
site_url: https://skyface753.github.io/Trainees-FiSi/
theme:
  name: material
  features:
    - content.code.copy
    # Disabled, because it prevents the js for the quiz from working
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
    - navigation.footer
    - navigation.expand
    - navigation.indexes
  palette:
    scheme: slate
markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - awesome-pages
  - git-revision-date
  - mkdocs_quiz
  - open-in-new-tab
  - print-site
  - thumbnails:
      style: margin-top:5px;margin-bottom:5px;margin-right:25px
nav:
  - Home:
      - index.md
  - ...
#   - First Start:
#       - first_start/index.md
#   - Mininet:
#       - ... | mininet/*.md
#   - Start - Virtualization:
#       - virtualization/virtualbox.md
#       - virtualization/proxmox.md
#       - virtualization/docker.md
#       - virtualization/kubernetes.md
#   - Networking:
#       - Basics:
#           - Subnetting: networking/basics/subnetting.md
#       - Firewall: networking/firewall.md
#       - Switch: networking/switch.md
#       - VLAN: networking/vlan.md
#   - Services:
#       - Intro: services/introduction.md
#       - ... | services/*.md
#   - Wifi:
#       - Controller: wifi/controller.md
#       - APs: wifi/aps.md
#   - VPN:
#       - ... | vpn/*.md
#   - Coding:
#       - ... | coding/*.md
#   - KI:
#       - ki/intro.md
#       - ... | ki/*.md
